language: node_js
node_js:
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
cache:
  directories:
    - node_modules
services:
  - mysql
before_script:
  - mysql -e 'create database sequelize_tokenify_test;'
branches:
  only:
    - master
